### ISSUE TITLE
Section 508 and NCI Style

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#69]
## 🤔 Tell Us About the Feature

The following issue is transliterated from an email from [Kara Smigel](mailto:smigelk@mail.nih.gov), Message-ID `<MN2PR09MB4971948DE2B925AB5A04194990200@MN2PR09MB4971.namprd09.prod.outlook.com>`.

## 🎇 What Solution You'd Like

In this email, Kara wrote:

> The Powerpoint attached runs down the 508 and NCI style guidelines that need to be followed on the EDRN website .  We tried to give a full technical explanation plus links to resources and guidelines to help make the changes.  I’ve also attached two files of the EDRN banner that is the “legal” one to use on the website: the .svg format, used for responsive websites, as well as a .png version suitable for desktop.  

## 〽️ Alternative Ideas

We can **ignore** the ideas that apply to development only (things like the development warning banner) and things that we can correct via content management interaction post-deployment.

## 🗺 Context

The email had these attached attachments:

A powerpoint:

[edrn-dev-issues-solutions-draft.pptx](https://github.com/EDRN/P5/files/5227145/edrn-dev-issues-solutions-draft.pptx)

An image:

![EDRN_54px-Logo-COLOR](https://user-images.githubusercontent.com/814813/93252580-4d593d00-f75b-11ea-8d47-b0d227afc862.png)

A SVG was promised but not included.

## ☑️ Tasks

- [x] Background color
- [x] Logo
- [x] DMCC Site and Log in placement
- [x] Search only in current section placement
- [x] DMCC site tooltip
- [x] "Home" color contrast
- [x] Down arrow on "About EDRN"
- [x] Menu bar changes during navigation (page 6)
- [x] Color contrast on gradient backgrounds
- [x] Color contrast on green tabs (Biomarker "Basics" tab, e.g.)
- [x] Color contrast on 〉 in breadcrumbs
- [x] Color contrast on hyperlink underline color
- [x] Table headers missing on informatics tools
- [x] Table padding missing
- [x] No rounded corners
- [x] Form elements must have labels (page 12)
- [x] Body font size too small (page 16)
- [x] Header progression (h1, h2, h3, …, page 18)
- [x] Remove underlining from "Biomarker Statistics" 
- [x] Mark visited links (page 21)
- [x] Remove "mailto" from email addresses
- [x] Indicate attached file types
- [x] Offsite link icon (page 26)
- [x] Footer links (pages 31–32)
- [x] High contrast home page redesign (page 33)
- [x] Typos (page 34)
- [x] In-development changes (page 35)

**Comment by nutjob4life** [comment]
In Message-ID `<DM8PR09MB7046AEEC5F959681D45C4C2BF7200@DM8PR09MB7046.namprd09.prod.outlook.com>`, 
[Wayne Randall](mailto:wayne.randall@nih.gov) followed up with two additional attachments.

[NCI-Digital-Style-Guide.pdf](https://github.com/EDRN/P5/files/5227161/NCI-Digital-Style-Guide.pdf)
[NCI-Branding-and-Logo-Use-Guide_5.pdf](https://github.com/EDRN/P5/files/5227166/NCI-Branding-and-Logo-Use-Guide_5.pdf)

**Comment by nutjob4life** [comment]
Ignoring "Color contrast on gradient backgrounds" as it refers to this banner:

![Screen Shot 2020-09-17 at 11 40 57 AM](https://user-images.githubusercontent.com/814813/93501157-adc2b880-f8da-11ea-8dd5-246ce0f979b0.png)

This only applies to in-development and demo sites—who cares about those! 😇

**Comment by nutjob4life** [comment]
As for "Form elements must have labels (page 12)", nothing we can do; I've [reported the issue](https://github.com/eea/eea.facetednavigation/issues/210) to the faceted navigation developers. For now we can take solace that the `<legend>` tells what the control is for by context even if it doesn't have an explicit `<label>`.

**Comment by nutjob4life** [comment]
These items are moved to their own issues:

- Indicate attached file types, #111 
- Offsite link icon #110 

There are _hereby marked as complete_ here, by the by.
